# Generated by Django 2.0.6 on 2018-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests_answers',
            name='answer_by_user',
            field=models.CharField(default='v', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tests_answers',
            name='correct_answer',
            field=models.CharField(default='v', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tests_answers',
            name='ques_id',
            field=models.CharField(default='3', max_length=10),
        ),
    ]
