# Generated by Django 2.0.6 on 2018-06-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20180617_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests_answers',
            name='answer_by_user',
        ),
        migrations.RemoveField(
            model_name='tests_answers',
            name='correct_answer',
        ),
    ]
