# Generated by Django 2.0.6 on 2018-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20180617_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests_answers',
            name='answer_by_user',
            field=models.CharField(default='v', max_length=1000),
        ),
        migrations.AddField(
            model_name='tests_answers',
            name='correct_answer',
            field=models.CharField(default='v', max_length=1000),
        ),
    ]
