# Generated by Django 2.0.6 on 2018-07-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_homecategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategories',
            name='reference_id',
            field=models.CharField(default='v', max_length=5),
        ),
    ]
