# Generated by Django 2.0.1 on 2018-03-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20180317_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1, unique=True)),
                ('slug2', models.SlugField(blank=True, editable=False, max_length=3)),
                ('slug3', models.SlugField(blank=True, editable=False)),
                ('slug4', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
