# Generated by Django 2.0.6 on 2018-07-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20180701_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tests_Answers',
        ),
    ]
