# Generated by Django 2.0.1 on 2018-03-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
