# Generated by Django 2.0.1 on 2018-03-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
