# Generated by Django 2.0.1 on 2018-03-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20180319_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
    ]
